import { StyleSheet } from 'react-native'

export const sharedStyle = StyleSheet.create({
    absolute: {position: "absolute"},
    absoluteFill: StyleSheet.absoluteFillObject,
    flex: { flex: 1 },
    flexGrow: { flexGrow: 1 },
    flexNoGrow: { flexGrow: 0 },
    flexWrap: { flexWrap: 'wrap' },
    flexNoWrap: { flexWrap: 'nowrap' },
    flexShrink0: { flexShrink: 0 },
    flexShrink1: { flexShrink: 1 },
    horizontal: { flexDirection: 'row' },
    horizontalReverse: { flexDirection: 'row-reverse' },
    vertical: { flexDirection: 'column' },
    verticalReverse: { flexDirection: 'column-reverse' },
    alignItemsCenter: { alignItems: 'center' },
    alignItemsFlexEnd: { alignItems: 'flex-end' },
    alignItemsFlexStart: { alignItems: 'flex-start' },
    alignSelfCenter: { alignSelf: 'center' },
    alignSelfFlexEnd: { alignSelf: 'flex-end' },
    alignSelfFlexStart: { alignSelf: 'flex-start' },
    alignSelfStretch: { alignSelf: 'stretch' },
    displayFlex: { display: 'flex' },
    displayNone: { display: 'none' },
    fullHeight: { height: '100%' },
    fullMinWidth: { minWidth: '100%' },
    fullMaxWidth: { maxWidth: '100%' },
    fullWidth: { width: '100%' },
    justifyContentCenter: { justifyContent: 'center' },
    justifyContentFlexEnd: { justifyContent: 'flex-end' },
    justifyContentFlexStart: { justifyContent: 'flex-start' },
    justifyContentSpaceBetween: { justifyContent: 'space-between' },
    justifyContentSpaceEvenly: { justifyContent: 'space-evenly' },
    margin: { margin: 16 },
    marginHalf: { margin: 16 / 2 },
    marginHorizontal: { marginHorizontal: 16 },
    marginHorizontalHalf: { marginHorizontal: 16 / 2 },
    marginHorizontalQuarter: { marginHorizontal: 16 / 4 },
    marginVertical: { marginVertical: 16 },
    marginVerticalHalf: { marginVertical: 16 / 2 },
    marginVerticalQuarter: { marginVertical: 16 / 4 },
    muted: { opacity: 0.6 },
    superMuted: { opacity: 0.1 },
    opacity0: { opacity: 0 },
    opacity100: { opacity: 1 },
    overflowHidden: { overflow: 'hidden' },
    overflowVisible: { overflow: 'visible' },
    padding: { padding: 16 },
    paddingHalf: { padding: 16 / 2 },
    paddingHorizontal: { paddingHorizontal: 16 },
    paddingHorizontalHalf: { paddingHorizontal: 16 / 2 },
    paddingHorizontalQuarter: { paddingHorizontal: 16 / 4 },
    paddingHorizontalNone: { paddingHorizontal: 0 },
    paddingVertical: { paddingVertical: 16 },
    paddingVerticalHalf: { paddingVertical: 16 / 2 },
    paddingVerticalQuarter: { paddingVertical: 16 / 4 },
    paddingVerticalNone: { paddingVertical: 0 },
    textCenter: { textAlign: 'center' },
    brandOrangeText: {color: '#FF6026'},
    brandOrangeBackground: {backgroundColor: '#FF6026'},
    center: {
      alignContent: 'center',
      alignItems: 'center',
      justifyContent: 'center',
    },
  
    horizontalAndVerticallyAligned: {
      flexDirection: 'row',
      alignContent: 'center',
      alignItems: 'center',
    },
    errorText: {
      marginLeft: 'auto',
      marginRight: 'auto',
      marginVertical: 12,
      color: 'red',
      fontSize: 20,
      fontFamily: 'Mulish-Regular'
    }
})